# Generated by Django 6.1 on 2026-10-09 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_chatlog_whatsapp_message_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('GROCERY', 'Daily Grocery'), ('FANCY', 'Fancy & Cosmetics'), ('GIFT', 'Gifts & Toys'), ('HARDWARE', 'Hardware & Cement'), ('STATIONERY', 'Stationery')], default='GROCERY', max_length=15),
        ),
    ]
