# Generated by Django 6.1 on 2026-10-10 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('GROCERY', 'Daily Grocery'), ('FANCY', 'Fancy & Cosmetics'), ('GIFT', 'Gifts & Toys'), ('STATIONERY', 'Stationery')], default='GROCERY', max_length=15),
        ),
    ]
